import type { FriendLink, FriendsPageConfig } from "../types/friendsConfig";

// 可以在src/content/spec/friends.md中编写友链页面下方的自定义内容

// 友链页面配置
export const friendsPageConfig: FriendsPageConfig = {
	// 页面标题，如果留空则使用 i18n 中的翻译
	title: "友链墙",

	// 页面描述文本，如果留空则使用 i18n 中的翻译
	description: "",

	// 是否显示底部自定义内容（friends.mdx 中的内容）
	showCustomContent: false, 	// 本站信息、申请表单、注意事项已内联，故关闭

	// 是否显示评论区，需要先在commentConfig.ts启用评论系统
	showComment: false,

	// 是否开启随机排序配置，如果开启，就会忽略权重，构建时进行一次随机排序
	randomizeSort: false,

	// 本站点信息（用于友链申请表单，请改为你自己的站点信息）
	site: {
		name: "Hyde Blog",
		desc: "人心中的成见是一座大山",
		url: "https://seasir.top",
		avatar: "https://seasir.top/assets/avatar.avif",
	},

	// 注意事项
	notes: [
		{
			title: "互换原则",
			content: "请先将本站添加到您的友链页面，确认后会添加您的友链",
		},
		{
			title: "链接维护",
			content: "友链网站长期无法访问或内容违规，将会被移除",
		},
		{
			title: "内容要求",
			content: "内容积极向上，不含有任何含色情/反动/暴力等违法违规内容",
		},
		{
			title: "站点要求",
			content: "支持 HTTPS，以原创内容为主，能够正常访问且有持续更新",
		},
		{
			title: "通过审核",
			content: "工作日 48 小时内，节假日顺延",
		},
	],
};

// 友链配置
export const friendsConfig: FriendLink[] = [
	{
		title: "Hyde Blog",
		desc: "人心中的成见是一座大山",
		siteurl: "https://seasir.top/",
		imgurl: "/assets/avatar.avif",
		tags: ["Astro"],
		weight: 10,
		enabled: true,
	},
	{
		title: "Firefly Docs",
		desc: "Firefly主题模板文档",
		siteurl: "https://docs-firefly.cuteleaf.cn",
		imgurl: "https://docs-firefly.cuteleaf.cn/logo.png",
		tags: ["Docs"],
		weight: 10,
		enabled: true,
	},
	{
		title: "宇阳",
		desc: "记录所学知识，缩短和大神的差距！",
		siteurl: "https://liuyuyang.net",
		imgurl:"https://q1.qlogo.cn/g?b=qq&nk=3311118881&s=640",
		tags: ["Blog"],
		weight: 8,
		enabled: true,
	},
	{
		title: "W3C技术联盟",
		desc: "让Web服务全人类",
		siteurl: "https://image.js.cn/",
		imgurl: "https://image.js.cn/logo.svg",
		tags: ["Astro"],
		weight: 8,
		enabled: true,
	},
	{
		title: "One",
		desc: "上海修车spa足浴推拿反差狂魔one哥",
		siteurl: "https://onedayxyy.cn/",
		imgurl:"https://img.onedayxyy.cn/images/Teek/Teekwebsite/xyy-logo.avif?w=150&h=150&fit=crop&fm=webp&q=80",
		tags: ["Blog"],
		weight: 8,
		enabled: true,
	},
	{
		title: "十三",
		desc: "欲买桂花同载酒，终不似，少年游。",
		siteurl: "https://blog.nw177.cn",
		imgurl: "https://img.nw177.cn/blog/100.assets/avatar.webp",
		tags: ["Astro"],
		weight: 8,
		enabled: true,
	},
	{
		title: "像风 Blog",
		desc: "相遇不过一场恩泽",
		siteurl: "https://astro.cchaoka.cn/",
		imgurl: "https://astro.cchaoka.cn/assets/avatar.avif",
		tags: ["Astro"],
		weight: 8,
		enabled: true,
	},
	{
		title: "楠枝小笺",
		desc: "安安静静地存在，就已经很好了。",
		siteurl: "https://www.nannax.top/",
		imgurl:"https://www.nannax.top/themes/Ethereal/assets/images/demo-avatar.png?width=800",
		tags: ["Astro"],
		weight: 8,
		enabled: true,
	},
	{
		title: "Yubendan",
		desc: "内心充盈者，独行也如众。",
		siteurl: "https://yubendan.com/",
		imgurl: "https://yubendan.com/_astro/avatar.DVGZ46-Q_1TAarN.webp",
		tags: ["Astro"],
		weight: 8,
		enabled: true,
	},
	{
		title: "versus0",
		desc: "技术+算法blog。",
		siteurl: "https://blog.542000.xyz",
		imgurl:"https://img.542000.xyz/file/friend_avatar/1778931720838_f167cb95af9d881f4378b92b3e181d89_4647054993754934443.jpg",
		tags: ["Astro"],
		weight: 8,
		enabled: true,
	},
	{
		title: "ZhiJing's Blog",
		desc: "Go with the flow.",
		siteurl: "https://iwexe.top",
		imgurl: "https://iwexe.top/avatar.svg",
		tags: ["Blog"],
		weight: 8,
		enabled: true,
	},
	{
		title: "星遐蝶梦",
		desc: "星穹漫遐，蝶携清梦。",
		siteurl: "https://blog.casto.top",
		imgurl: "https://blog.casto.top/_astro/avatar.BmbZMO2d_Z1ed0Se.webp",
		tags: ["Astro"],
		weight: 8,
		enabled: true,
	},
	{
		title: "团子和蛋糕",
		desc: "如果你喜欢那么欢迎来到我的世界！",
		siteurl: "https://blog.tsh520.cn",
		imgurl: "https://re.tsh520.cn/zl/tx.webp",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "年华",
		desc: "分享生活和技术。",
		siteurl: "https://blog.520781.xyz",
		imgurl: "https://q1.qlogo.cn/g?b=qq&nk=1323860289&s=640",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "THW's Blog",
		desc: "前途似海，来日方长",
		siteurl: "https://blog.tianhw.top",
		imgurl: "https://image.tianhw.top/avatar.webp",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "番茄主理人",
		desc: "坐而言不如起而行.",
		siteurl: "https://fqzlr.com/",
		imgurl: "https://q1.qlogo.cn/g?b=qq&nk=20447289&s=640",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "晓正杨博客",
		desc: "让代码更有价值，让学生生活不再枯燥",
		siteurl: "https://blog.7003410.xyz/",
		imgurl: "https://images.sy.fj.kg/logo.96adlmmyni.webp",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "小王的博客",
		desc: "一个上了年纪的猿人.",
		siteurl: "https://www.huhaha.vip/",
		imgurl: "https://www.huhaha.vip/acatar.webp",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "Sigrika-善良耙耙柑🍊",
		desc: "记录我的二次元之旅",
		siteurl: "https://qwq.sigrika.cc/",
		imgurl:"https://weavatar.com/avatar/bc0dba25ea5949e8290d012e081ceec669aa7784c7ad765173473c80cbaee404",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "Nachcekoの小窝",
		desc: "1つの熱愛の2次元の小さい萌の新しい~ /.こんにちはnya~です",
		siteurl: "https://tbmiao.dpdns.org",
		imgurl: "https://avatars.githubusercontent.com/u/172878250?v=4",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "Saimen Blog",
		desc: "读史可以明智,知古方能鉴今。",
		siteurl: "https://com.z2m.store",
		imgurl: "https://com.z2m.store/img/butterfly-icon.png",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "新锐博客",
		desc: "记录学习与分享资源",
		siteurl: "https://blog.xrbk.cn",
		imgurl: "https://blog.xrbk.cn/favicon.png",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "Eysnter",
		desc: "你好",
		siteurl: "https://blog.eysnter.cn/",
		imgurl: "https://img.eysnter.cn/file/posts/icon/1780993886377_0122.webp",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "小生",
		desc: "天生我材必有用，千金散尽还复来。",
		siteurl: "https://www.zsso.cn",
		imgurl: "https://t.alcy.cc/tx",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "mccsjs",
		desc: "点一盏灯，等待一个迷路的夜🍁",
		siteurl: "https://blog.seln.cn",
		imgurl: "https://blog.seln.cn/img/ico.jpg",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "橘智",
		desc: "共享博客&深度思考",
		siteurl: "https://juzhiart.com",
		imgurl: "https://dataer-1257252871.cos.ap-shanghai.myqcloud.com/virtualUserIcon/logo.png",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "顾拾柒",
		desc: "分享、实践、学习",
		siteurl: "https://blog.olinl.com",
		imgurl: "https://blog.olinl.com/assets/images/avatar.webp",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "石猫博客",
		desc: "就叫石猫好啦...",
		siteurl: "https://blog.imshimao.com",
		imgurl: "https://img.cdn1.vip/i/6a811517810a6_1786844439.jpg",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "TT清沫uk",
		desc: "Enjoy life",
		siteurl: "https://ttquk.github.io",
		imgurl: "https://ts1.tc.mm.bing.net/th/id/OIP-C.6WsD9caLSNQFhJOi77soRAHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "JerryLife",
		desc: "Enjoy life",
		siteurl: "https://jerry-nis.top",
		imgurl: "https://free.picui.cn/free/2026/07/16/6a58eb63ecbd1.png",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "Fiee’s Blog",
		desc: "长风破浪会有时，直挂云帆济沧海",
		siteurl: "https://www.aifiee.cn",
		imgurl: "https://aifiee-blog.oss-cn-beijing.aliyuncs.com/blog/images/1782719333889_1414.jpg",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "毛",
		desc: "如果有不可能，那就去创造！海",
		siteurl: "https://blog.huchao.vip/",
		imgurl: "https://img.huchao.vip/file/avatar/1781199555294_favicon.ico",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "虚无缥缈",
		desc: "Hello, I'm XuWuPiaoMiao.",
		siteurl: "https://blog.xuwupiaomiao.cn/",
		imgurl: "https://blog.xuwupiaomiao.cn/_astro/avatar.BcAu2wMi_yT6PR.webp",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "JustPureH2O 的博客",
		desc: "穷方圆平直之情，尽规矩准绳之用",
		siteurl: "https://justpureh2o.cn",
		imgurl: "https://justpureh2o.cn/avatar.jpg",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "L!!!!ght",
		desc: "阳光正好，慢慢前行。",
		siteurl: "https://sunlight.kejk.cn",
		imgurl: "https://easyimg.kejk.cn/i/4484873c-c2cc-4b3d-bc35-5c72ed01cfd9.webp",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "Elykia",
		desc: "致以无瑕之人",
		siteurl: "https://blog.elykia.cn/",
		imgurl: "https://bu.dusays.com/2024/10/25/671b2438203a6.gif",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "奶昔的小窝",
		desc: "死宅一枚",
		siteurl: "https://naixv.netlify.app/",
		imgurl: "https://p26-sign.douyinpic.com/tos-cn-i-0813c001/oUvA5DiftEBdowAAX2Agf4i1n9IH9YcANA9qSC~tplv-dy-shrink:640:567.webp?lk3s=138a59ce&x-expires=1785560400&x-signature=YpoicADrwq9L59vNzo%2FXuDXBhoQ%3D&from=327834062&s=PackSourceEnum_DOUYIN_REFLOW&se=true&sh=640_567&sc=image&biz_tag=aweme_images&l=20260702135913037381C6C9813F40CA22",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "轻笑Chuckle",
		desc: "漫天倾尘,风中轻笑",
		siteurl: "https://www.qcqx.cn",
		imgurl: "https://www.qcqx.cn/head.webp",
		tags: ["Blog"],
		weight: 0,
		enabled: true,
	},
	{
		title: "张小阳",
		desc: "业精于勤荒于嬉，行成于思毁于随。",
		siteurl: "https://www.zzyang.top/",
		imgurl: "https://www.zzyang.top/favicon/avatar.png",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
		{
		title: "RyuChan",
		desc: "Ciallo～(∠・ω<)⌒★",
		siteurl: "https://ryu-chan.vercel.app/",
		imgurl: "https://ryu-chan.vercel.app/profile.png",
		tags: ["Astro"],
		weight: 0,
		enabled: true,
	},
	{
		title: "Mizuki",
		desc: "下一代Material Design 3 博客主题(Astro驱动)",
		siteurl: "https://mizuki.mysqil.com/",
		imgurl: "https://mizuki.mysqil.com/_astro/avatar.DodcwRNI_ZrnMU5.webp",
		tags: ["Astro"],
		weight: 8,
		enabled: true,
	},
	{
		title: "Mizuki-Ultra",
		desc: "一个简约&功能丰富的 Astro 博客 主题",
		siteurl: "https://docs.mizuki.mysqil.com/",
		imgurl: "https://docs.mizuki.mysqil.com/favicon.png",
		tags: ["Docs"],
		weight: 8,
		enabled: true,
	},
];

// 获取启用的友链并进行排序
export const getEnabledFriends = (): FriendLink[] => {
	const friends = friendsConfig.filter((friend) => friend.enabled);

	if (friendsPageConfig.randomizeSort) {
		return friends.sort(() => Math.random() - 0.5);
	}

	return friends.sort((a, b) => b.weight - a.weight);
};
